### ISSUE TITLE
Release version 0.5 to the SCC

### ISSUE THREAD

**Issue by bu-bgregor** [rcs-si/module_check#6]
Let's call this version 0.5.  Aside from some polishing the following functionality is working:

* test if a module is loadable (i.e. no Lua or Tcl syntax errors)
* test if the variables shown in "module help" and when the module is loaded are the same.

To do to release a usable version:

* Remove any extraneous print statements
* Add command line support:
```
# -c means "check this module"
module_check.py -c module/version 
``` 
* If the module/version directory does not exist in /share/pkg.8, raise an exception and stop.

Once that works:
 * Tag the code in github as v0.5
 * gets its own module, `/share/pkg.8/module_check/0.5`
 * get a link in `/share/module.8/rcstools`
 * is then usable by RCS with:
 ```
 module use /share/module.8/rcstools
module load module_check
module_check.py -c modname/version
```

**Comment by katgit** [comment]
@bu-bgregor Do you think it would make sense to "rename" the executable from "module_check.py" to "module_check"? The way we did it in 2 other projects is we created a bash script with the same name and this bash script would load appropriate python module (if needed) and then call python script with the passed arguments. 
I am not sure if this is a good solution, but it is easier to remember (than remembering that the tool was written in python)

**Comment by bu-bgregor** [comment]
Extra To Do:

- Add a wrapper script "module_check" that actually calls module_check.py

**Comment by bu-bgregor** [comment]
module_check wrapper is added.  Module is installed at /share/pkg.8/module_check and is linked in /share/module.8/rcstools/module_check

The 0.5 release has a bug which will be described in a new issue.
